// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/dogkerr/mailing-service/m/v2/config"
	"github.com/dogkerr/mailing-service/m/v2/internal/rest"
	"github.com/dogkerr/mailing-service/m/v2/pkg"
	"github.com/hertz-contrib/pprof"
)

func main() {
	cfg, err := config.NewConfig()
	if err != nil {
		hlog.Fatalf("Config error: %s", err)
	}
	logsCores := pkg.InitZapLogger(cfg)
	defer logsCores.Sync()
	hlog.SetLogger(logsCores)

	// validation error custom
	customValidationErr := pkg.CreateCustomValidationError()
	h := server.Default(
		server.WithHostPorts("0.0.0.0:9898"),
		server.WithValidateConfig(customValidationErr),
		server.WithExitWaitTime(4*time.Second),
	)
	h.Use(pkg.AccessLog())
	//  harusnya tambahin svc
	rest.EmailRouter(h)
	pprof.Register(h)

	h.Spin()
}
